### ISSUE TITLE
calabash 2.0 Unable to launch simulator and get the application to run using below command

### ISSUE THREAD

**Issue by tejasv02** [calabash/Calabash-2.0-x-platform#6]
CAL_DEBUG_CALLED_METHODS=1 CAL_DEVICE_ID='iPhone 6 (9.0)' CAL_DEBUG=1 CAL_APP=features/prebuilt/ios.app bundle exec cucumber -p ios --tags  @info

I have clone your project and tried to get that running on my machine.

I see below log message :

```
Setting Android SDK location to $ANDROID_HOME
Android SDK location set to '/Users/xxx/Documents/android-sdk-macosx'
Set aapt path to '/Users/xxx/Documents/android-sdk-macosx/build-tools/23.0.1/aapt'
Set zipalign path to '/Users/xx/Documents/android-sdk-macosx/build-tools/23.0.1/zipalign'
Set adb path to '/Users/xx/Documents/android-sdk-macosx/platform-tools/adb'
Set android jar path to '/Users/xx/Documents/android-sdk-macosx/platforms/android-23/android.jar'
Setting Java SDK location to $JAVA_HOME
Java SDK location set to '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home'
Found java on PATH
Set java path to '/usr/bin/java'
Found keytool on PATH
Set keytool path to '/usr/bin/keytool'
Found jarsigner on PATH
Set jarsigner path to '/usr/bin/jarsigner'
Using the ios profile...
Feature: Initial experience
  As a user I want a helpful and simple initial
  experience with the app. I should be able to get help
  and login to an existing WordPress site.

  @info @reinstall
  Scenario: Obtaining more information         # features/login.feature:7
 uninitialized constant RunLoop::Simctl::Bridge (NameError)
 ./features/support/hooks.rb:75:in `reset'
 ./features/support/hooks.rb:49:in `on_new_scenario'
 ./features/support/hooks.rb:8:in `Before'
```

*my Gem list

```
calabash (1.9.9.pre3, 1.9.9.pre1)
calabash-android (0.5.14, 0.5.7)
calabash-common (0.0.2)
calabash-cucumber (0.16.3, 0.16.2)
calahelper (0.0.1)
CFPropertyList (2.3.2, 2.3.1)
claide (0.9.1, 0.7.0)
clipboard (1.0.6)
cocoapods (0.38.2, 0.35.0)
cocoapods-core (0.38.2, 0.35.0)
cocoapods-downloader (0.9.3, 0.8.1)
cocoapods-plugins (0.4.2, 0.3.2)
cocoapods-stats (0.5.3)
cocoapods-trunk (0.6.4, 0.4.1)
cocoapods-try (0.4.5)
coderay (1.1.0)
colored (1.2)
colorize (0.7.7)
command_runner_ng (0.1.0, 0.0.2)
cucumber (2.1.0)
cucumber-core (1.3.0, 1.2.0)
diff-lcs (1.2.5)
edn (1.1.0)
escape (0.0.4)
ethon (0.8.0)
executable-hooks (1.3.2)
faraday (0.9.2)
faraday_middleware (0.10.0)
ffi (1.9.10)
formatador (0.2.5)
fuzzy_match (2.0.4)
gem-wrappers (1.2.7)
geocoder (1.2.11, 1.2.9)
gh (0.14.0)
gherkin (2.12.2)
gherkin3 (3.1.2)
git (1.2.9.1)
growl (1.0.3)
guard (2.13.0)
guard-bundler (2.1.0)
guard-compat (1.2.1)
guard-rspec (4.6.4)
highline (1.7.7)
httpclient (2.6.0.1)
i18n (0.7.0)
io-console (0.4.2)
jruby-openssl (0.9.4)
json (1.8.3, 1.8.1)
launchy (2.4.3)
listen (3.0.3)
lucene (0.5.0.beta.1)
luffa (1.1.0, 1.0.7)
lumberjack (1.0.9)
method_source (0.8.2)
minitest (5.8.1, 5.8.0, 5.7.0, 4.7.5)
molinillo (0.3.1, 0.1.2)
multi_json (1.11.2)
multi_test (0.1.2)
multipart-post (2.0.0)
nap (0.8.0)
nenv (0.2.0)
net-ftp-list (3.2.8)
net-http-persistent (2.9.4)
net-http-pipeline (1.0.1)
net-sftp (2.1.2)
net-ssh (2.9.2)
netrc (0.7.8)
notiffany (0.0.8)
open4 (1.3.4)
plugin_manager (1.5)
pry (0.10.3, 0.10.1, 0.9.12.6)
pry-nav (0.2.4)
psych (2.0.2)
pusher-client (0.6.2)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.4.2, 10.1.0)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rdoc (4.1.0)
redcar-bundles (0.3)
redcar-icons (0.3)
redcar-javamateview (0.2)
redcar-jruby (0.1)
redcar-svnkit (0.2)
rubygems-bundler (1.4.4)
rubygems-update (2.4.8)
rubysl-rexml (2.0.4)
rubyzip (1.1.7)
run_loop (1.5.6, 1.5.5, 1.5.4, 1.4.1)
```

**Comment by jmoody** [comment]
@tejasv02 

>  uninitialized constant RunLoop::Simctl::Bridge (NameError)

The run-loop API has changed.  I haven't had any time to update Calabash 2.0.

You can update the project to use RunLoop::CoreSimulator instead of RunLoop::Simctl::Bridge, but I think there are likely other problems.
